#!/bin/bash
#
#

cfgdir=$(cd "`dirname $0`" ; pwd)


# Test case mapping table
declare -A case_map
case_map=(
["codecase"]="on" 
["gid-ip"]="off" 
["gid-mac"]="off" 
["RoceSend"]="on" 
["RdmaRead"]="off" 
["RdmaWrite"]="off" 
["SupportPD"]="off" 
["SupportQP"]="off" 
["SupportCQ"]="off" 
["SupportMR"]="off"
["platformdev"]="off"
["SupportXGE"]="off" 
)
# code case index
START_INDEX=0
END_INDEX=3


# Common tools directory path
COMMON_TOOL_PATH="common_tool"

# Test case code directory path
TEST_CASE_PATH=${cfgdir}"/case_script"
CASEPATH="roce-test"

# Start the machine environment IP
BACK_IP=192.168.1.250

tmp1=`dmesg | grep -i "renamed from eth3" -w`
tmp2=`echo ${tmp1%:*}`
ROCE_ETH3=`echo ${tmp2##* }`

ifconfig $ROCE_ETH3 192.168.3.64 netmask 255.255.255.0

tmp3=`ethtool $ROCE_ETH3 | grep -i "link detected" -w`
IS_ETH3_OK=`echo ${tmp3##* }`
