#!/bin/bash
#
#

declare -A eth_map
eth_map=(
["eth0"]="eth0"
["eth1"]="eth1"
["eth2"]="eth2"
["eth3"]="eth3"
)

#we update the eth rename info here
for i in ${!eth_map[*]}
do
	tmp=`dmesg | grep -i "renamed from "$i -w`
	tmp=`echo ${tmp%:*}`
	tmp=`echo ${tmp##* }`
        eth_map[$i]=$tmp
	echo "The name of "$i" is renamed as "${eth_map[$i]}
done

# Test case mapping table
declare -A case_map
case_map=(
["iperf_ge_port"]="off" 
["iperf_xge_port"]="off"
["ping6_GE"]="off"
["ifconfigtest"]="on"
["checksum_offload"]="on"
)

#Number of threads
thread=(1 3 5 10 20) 

#iperf run time
time=80

# Common tools directory path
COMMON_TOOL_PATH="common_tool"

# Test case code directory path
TEST_CASE_PATH="xge_autotest/case_script"

# Start the machine environment IP
BACK_IP=192.168.1.200


tmp=`dmesg | grep -i "renamed from eth1" -w`
tmp1=`echo ${tmp%:*}`
HNS_ETH1=`echo ${tmp1##* }`

HNS_MIP="192.168.3.60"
HNS_SIP="192.168.3.61"
